"""Add shortname to school

Revision ID: 048a41ffcb23
Revises: a0e221bdda9b
Create Date: 2023-12-08 13:27:21.714590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048a41ffcb23'
down_revision = 'a0e221bdda9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('short')

    # ### end Alembic commands ###
