"""Role model

Revision ID: 05d65b6dcf84
Revises: 7c6690ac494c
Create Date: 2023-11-28 16:50:19.689823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d65b6dcf84'
down_revision = '7c6690ac494c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('pension', sa.String(length=12), nullable=True),
    sa.Column('ftpt', sa.String(length=20), nullable=True),
    sa.Column('weekhours', sa.Float(), nullable=True),
    sa.Column('contract', sa.String(length=80), nullable=True),
    sa.Column('holiday', sa.String(length=80), nullable=True),
    sa.Column('notice', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
