"""Remove role from staff model

Revision ID: 07c7662a6464
Revises: 4dde93b13070
Create Date: 2023-11-30 21:58:11.244253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07c7662a6464'
down_revision = '4dde93b13070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
