"""Add status to r2r

Revision ID: 6ba7220d0cdb
Revises: 9cd252d3a50c
Create Date: 2023-11-28 11:11:41.307655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba7220d0cdb'
down_revision = '9cd252d3a50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
