"""replace native requests with external model

Revision ID: 7c6690ac494c
Revises: 82e2e31091e5
Create Date: 2023-11-28 15:18:03.805506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c6690ac494c'
down_revision = '82e2e31091e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('r2_r_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('request_date')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('variation_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('request_date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('request_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variation_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('request_id')

    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('request_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('r2_r_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('request_id')

    with op.batch_alter_table('onboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
