"""Variation and r2r now link to role model

Revision ID: 895f63af4f69
Revises: 05d65b6dcf84
Create Date: 2023-11-30 16:51:43.528877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '895f63af4f69'
down_revision = '05d65b6dcf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('r2_r_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('r2_r_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('department_id')
        batch_op.drop_column('salary')
        batch_op.drop_column('contract')
        batch_op.drop_column('school_id')
        batch_op.drop_column('holiday')
        batch_op.drop_column('weekhours')
        batch_op.drop_column('ftpt')
        batch_op.drop_column('notice')
        batch_op.drop_column('pension')
        batch_op.drop_column('role')

    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('variation_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('variation_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('department_id')
        batch_op.drop_column('salary')
        batch_op.drop_column('contract')
        batch_op.drop_column('holiday')
        batch_op.drop_column('weekhours')
        batch_op.drop_column('ftpt')
        batch_op.drop_column('notice')
        batch_op.drop_column('pension')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pension', mysql.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('notice', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ftpt', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('weekhours', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('holiday', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('contract', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('salary', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variation_ibfk_1', 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key('variation_ibfk_3', 'staff', ['staff_id'], ['id'])
        batch_op.drop_column('role_id')

    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('pension', mysql.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('notice', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ftpt', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('weekhours', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('holiday', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contract', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('salary', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('r2_r_ibfk_3', 'school', ['school_id'], ['id'])
        batch_op.create_foreign_key('r2_r_ibfk_1', 'department', ['department_id'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
