"""Removed staff role columns

Revision ID: a0e221bdda9b
Revises: bb4e9dc34106
Create Date: 2023-12-08 12:54:59.845814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0e221bdda9b'
down_revision = 'bb4e9dc34106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('staff_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('staff_ibfk_1', type_='foreignkey')
        batch_op.drop_column('pension')
        batch_op.drop_column('notice')
        batch_op.drop_column('department_id')
        batch_op.drop_column('ftpt')
        batch_op.drop_column('school_id')
        batch_op.drop_column('salary')
        batch_op.drop_column('contract')
        batch_op.drop_column('job')
        batch_op.drop_column('weekhours')
        batch_op.drop_column('holiday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holiday', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('weekhours', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('job', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('contract', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('salary', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ftpt', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notice', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('pension', mysql.VARCHAR(length=12), nullable=True))
        batch_op.create_foreign_key('staff_ibfk_1', 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key('staff_ibfk_2', 'school', ['school_id'], ['id'])

    # ### end Alembic commands ###
