"""Added Staff model

Revision ID: b0229727bba4
Revises: 77d9d8e4d717
Create Date: 2023-11-13 10:07:54.618946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0229727bba4'
down_revision = '77d9d8e4d717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nino', sa.String(length=12), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('pension', sa.String(length=12), nullable=True),
    sa.Column('ftpt', sa.String(length=20), nullable=True),
    sa.Column('weekhours', sa.Float(), nullable=True),
    sa.Column('contract', sa.String(length=80), nullable=True),
    sa.Column('holiday', sa.String(length=80), nullable=True),
    sa.Column('notice', sa.String(length=20), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    # ### end Alembic commands ###
