"""add status to variation

Revision ID: ba6332e720f6
Revises: f92c8e5c60cd
Create Date: 2023-11-28 14:22:40.316060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6332e720f6'
down_revision = 'f92c8e5c60cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
