"""Add old role to variation

Revision ID: bb4e9dc34106
Revises: f591c3f9fcc1
Create Date: 2023-12-06 16:21:57.268512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb4e9dc34106'
down_revision = 'f591c3f9fcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_role_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('variation_ibfk_5', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['old_role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['new_role_id'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variation_ibfk_5', 'role', ['role_id'], ['id'])
        batch_op.drop_column('old_role_id')
        batch_op.drop_column('new_role_id')

    # ### end Alembic commands ###
