"""Add messages to r2r

Revision ID: f4fd98ac74c0
Revises: 05a255cd111c
Create Date: 2023-11-22 15:40:58.483224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fd98ac74c0'
down_revision = '05a255cd111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r2_r_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r2r_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['r2r_id'], ['r2_r.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r2_r_message')
    # ### end Alembic commands ###
