"""Removed approved from r2r

Revision ID: f9397f3648d7
Revises: 6ba7220d0cdb
Create Date: 2023-11-28 11:17:08.724587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9397f3648d7'
down_revision = '6ba7220d0cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('r2_r', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
